version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: link-ninja
    ports:
      - '8082:80'
      - '8443:443'
    volumes:
      - ./dist:/usr/local/apache2/htdocs
      - ./docker/ssl:/usr/local/apache2/ssl
      - ./docker/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./docker/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    entrypoint: ["/docker-entrypoint.sh"]
    restart: unless-stopped